services:
  chronograf:
    container_name: chronograf
    image: chronograf:latest
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
  # see https://docs.influxdata.com/chronograf/v1.9/administration/config-options/
    - INFLUXDB_URL=http://influxdb:8086
  # - INFLUXDB_USERNAME=
  # - INFLUXDB_PASSWORD=
  # - INFLUXDB_ORG=
  # - KAPACITOR_URL=http://kapacitor:9092
    ports:
    - "8888:8888"
    volumes:
    - ./volumes/chronograf:/var/lib/chronograf
    depends_on:
    - influxdb
  # - kapacitor

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - TZ=Etc/UTC
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volumes/grafana/data:/var/lib/grafana
    - ./volumes/grafana/log:/var/log/grafana
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  influxdb2:
    container_name: influxdb2
    image: "influxdb:latest"
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    - DOCKER_INFLUXDB_INIT_USERNAME=me
    - DOCKER_INFLUXDB_INIT_PASSWORD=mypassword
    - DOCKER_INFLUXDB_INIT_ORG=myorg
    - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    - DOCKER_INFLUXDB_INIT_MODE=setup
  # - DOCKER_INFLUXDB_INIT_MODE=upgrade
    ports:
    - "8087:8086"
    volumes:
    - ./volumes/influxdb2/data:/var/lib/influxdb2
    - ./volumes/influxdb2/config:/etc/influxdb2
    - ./volumes/influxdb2/backup:/var/lib/backup
  # - ./volumes/influxdb.migrate/data:/var/lib/influxdb:ro
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  kapacitor:
    container_name: kapacitor
    image: kapacitor:1.5
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
  # see https://docs.influxdata.com/kapacitor/v1.6/administration/configuration/#kapacitor-environment-variables
    - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
  # - KAPACITOR_INFLUXDB_USERNAME=
  # - KAPACITOR_INFLUXDB_PASSWORD=
  # - KAPACITOR_HOSTNAME=kapacitor
  # - KAPACITOR_LOGGING_LEVEL=INFO
  # - KAPACITOR_REPORTING_ENABLED=false
    ports:
    - "9092:9092"
    volumes:
    - ./volumes/kapacitor:/var/lib/kapacitor
    depends_on:
    - influxdb

  mosquitto:
    container_name: mosquitto
    build:
      context: ./.templates/mosquitto/.
      args:
      - MOSQUITTO_BASE=eclipse-mosquitto:latest
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    ports:
    - "1883:1883"
    volumes:
    - ./volumes/mosquitto/config:/mosquitto/config
    - ./volumes/mosquitto/data:/mosquitto/data
    - ./volumes/mosquitto/log:/mosquitto/log
    - ./volumes/mosquitto/pwfile:/mosquitto/pwfile

  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    environment:
    - TZ=Etc/UTC
    ports:
    - "1880:1880"
    volumes:
    - ./volumes/nodered/data:/data
    - ./volumes/nodered/ssh:/root/.ssh
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
    - "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/vcio:/dev/vcio"
    - "/dev/gpiomem:/dev/gpiomem"

  telegraf:
    container_name: telegraf
    build: ./.templates/telegraf/.
    restart: unless-stopped
    environment:
    - TZ=Etc/UTC
    ports:
    - "8092:8092/udp"
    - "8094:8094/tcp"
    - "8125:8125/udp"
    volumes:
    - ./volumes/telegraf:/etc/telegraf
    - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
    - influxdb
    - mosquitto

